language: python
python:
  - 3.6.6
services:
  - docker
before_install:
  - cd capsulefyweb
install:
  - pip install -r requirements.txt
script:
  - "./manage.py test"
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push raffrearaus/capsutesting