language: python
python:
  - 3.6.6
services:
  - docker
before_install:
  - cd capsulefyweb
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . --tag raffrearaus/capsutesting
  - docker push raffrearaus/capsutesting