language: python
python:
- 3.6.6
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_d1eb42c1423f_key -iv $encrypted_d1eb42c1423f_iv
  -in aws-capsutesting.pem.enc -out aws-capsutesting.pem -d
- cd capsulefyweb
install:
- pip install -r requirements.txt
script:
- python manage.py test
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build . --tag raffrearaus/capsutesting
- docker push raffrearaus/capsutesting
- cd ..
- chmod 400 aws-capsutesting.pem
- ssh -o "StrictHostKeyChecking no" -i aws-capsutesting.pem ec2-34-233-121-249.compute-1.amazonaws.com
- cd capsutesting
- docker-compose pull
- docker-compose up -d
- exit
